### ISSUE TITLE
[BUG] Middleware not called while using nestjs-session with @nestjs/graphql

### ISSUE THREAD

**Issue by Nabellaleen** [iamolegga/nestjs-session#181]
**What is the current behavior?**

I don't succeed to make this package work with `@nestjs/graphql`.
When I call a REST route, it's working well, and the `session(req, res, next)` middleware (from `express-session`) is well called.
But when I call the GraphQL entrypoint, the middleware is not called at all.

I've digged deep in nestjs source-code, but I don't know really where to look.

Even with a `forRoutes: [{ path: '/*', method: RequestMethod.ALL }],` this change nothing.

**What is the expected behavior?**

In practice, the consequences are that no cookie is defined in the GraphQL response, and so, the sessions don't work.

**Please mention other relevant information such as Node.js version and Operating System.**

**Comment by iamolegga** [comment]
Could you please provide minimal example repo for me to quick jump into it?

**Comment by Nabellaleen** [comment]
I'll try to find the time to build an example but it's quite a big work, so I admit I'd hope you had an "intuition" about the problem before :p

I'll let you know !

**Comment by Nabellaleen** [comment]
Here is an example : https://github.com/Nabellaleen/hello-graphql-session-nestjs !

I've joined a Postman Collection to facilitate the things.

In fact, the problem is not limited to GraphQL and exists also with the REST approach.

To reproduce, you just have to do a `login` request, then a `me` request, and see what happens :
- The `login` request do the job well, the serializer is called and the user is well stored in the session
- But for the `me` request, passport seems to not retrieve the user from the session : the deserializer is not called, and the `request.user` is not populated

**Comment by Nabellaleen** [comment]
After putting some breakpoints in passport, and in particular here : https://github.com/jaredhanson/passport/blob/master/lib/strategies/session.js#L50

I see that passport base its behaviour on `req._passport.session` object ... which not exists !

**Comment by iamolegga** [comment]
What I can say just now without dive into it, is that you are using `passport.session` method that could lead to overwriting `session` value on `request`. Try to get rid of it, because it is not clean example of usage this library

**Comment by Nabellaleen** [comment]
Removing the `passport.session` is not working (no error, but no success :p)

In the passport documentation about sessions, they say :
```
 * Note that additional middleware is required to persist login state, so we
 * must use the `connect.session()` middleware _before_ `passport.initialize()`.
```

But, as @nestjs/passport not implementing the `passport.initialize()`, I have to do it by hand in main.js, and it is probably added "before" nestjs-session :/

I'll try by moving the passport.initialize into a module

**Comment by Nabellaleen** [comment]
But I confirm if I remove `nestjs-session` module, and directly use, in main.js :
```
  app.use(session({
    secret: 'a secret',
    name: 'abcd',
    resave: true,
    saveUninitialized: true
  }));
  app.use(passport.initialize());
  app.use(passport.session());
```

Everything works well

**Comment by Nabellaleen** [comment]
So, I've built a simple module to do the init and session, and it works well. So I think the problem is not from your side, but from @nestjs/passport side who should integrate a way to register these middlewares.
```
import {
    createModule,
    FacadeModuleStaticOptional
  } from 'create-nestjs-middleware-module';
import * as passport from 'passport';

interface Options {
    maxDuration?: number
}

export const PassportSessionModule = createModule<Options>(options => {
    return [
        passport.initialize(),
        passport.session(),
    ]
    // app.use(passport.initialize());
    // app.use(passport.session());
}) as FacadeModuleStaticOptional<Options>
```

**Comment by iamolegga** [comment]
> But I confirm if I remove `nestjs-session` module, and directly use, in main.js :
> 
> ```
>   app.use(session({
>     secret: 'a secret',
>     name: 'abcd',
>     resave: true,
>     saveUninitialized: true
>   }));
>   app.use(passport.initialize());
>   app.use(passport.session());
> ```
> 
> Everything works well

Is `session` came here from original `express-session` module?
Maybe problem with the order of middlewares execution? Ok, I'll dive into it in a few days

**Comment by Nabellaleen** [comment]
Yes, it's due to the order of the execution, so I've posted an issue, as mentioned, on nestjs/passport, because it's probably not to you to handle this case

**Comment by Nabellaleen** [comment]
Maybe you could help on the nestjs/passport issue https://github.com/nestjs/passport/issues/236

I could make a PR, but I've no idea about how to handle the problem, and with the work you've made on create-nestjs-middleware-module, I'm sure you're able to give me hints ;)

**Comment by robertwestbury** [comment]
Any update on this? My issue was closed as a "duplicate" but I'm not using passport or anything so I don't think it has anything to do with @Nabellaleen's issue. @iamolegga

**Comment by iamolegga** [comment]
@robertwestbury reopened your issue

**Comment by iamolegga** [comment]
@Nabellaleen any news? Just got some words from other person who is not using this module, but using `express-session` directly with `nestjs` and `@nestjs/passport`, and he has the same issue too. So, for now we can say that problem is on the side of `@nestjs/passport`. And this is not related to `graphql`. So I'm closing this issue, but feel free to keep discussion and inform me please on this

**Comment by Nabellaleen** [comment]
Yeah, +1, is fully due to `@nestjs/passport`, but they don't really care about this use case so ... 

How I've bypassed the problem is mentioned here : https://github.com/nestjs/passport/issues/236

**Comment by codejamninja** [comment]
@Nabellaleen I don't understand how to get graphql to use the session. Any suggestions?

**Comment by codejamninja** [comment]
I'm using redis to manage the session. It's really odd because the session in my controllers works great. However, with graphql, every request creates a brand new empty session.

_Session in Controllers_
![Screenshot from 2020-06-02 21-37-27](https://user-images.githubusercontent.com/6234038/83589464-66760f00-a519-11ea-8edf-09845ad01e60.png)

_Session in Graphql_
![Screenshot from 2020-06-02 21-37-38](https://user-images.githubusercontent.com/6234038/83589512-8279b080-a519-11ea-80c7-c7694ab5b411.png)

Notice that only the first session is used in the controller, but all the rest of the sessions are created new with every graphql request.
