### ISSUE TITLE
[QUESTION] Get Session from Graphql

### ISSUE THREAD

**Issue by codejamninja** [iamolegga/nestjs-session#234]
I'm not able to get the session from graphql.

`req.session` does not seem to work.

**Comment by iamolegga** [comment]
The problem is with graphql module, nest has not guaranty of middleware's order, so if `req.session` is undefined, it means `nestjs-session`'s middleware is not executed.

If you could provide repo with example I could try help with that.

**Comment by codejamninja** [comment]
Yes, here is my code.

https://github.com/codejamninja/appsaas-core/blob/master/src/app.module.ts#L54

You can run it with the following command. It will automatically run and setup the databases. (you will need docker and docker-compose setup on your computer)

```
yarn install
yarn run start
```

**Comment by codejamninja** [comment]
Here is where I am trying to access the session.

https://github.com/codejamninja/appsaas-core/blob/master/src/resolvers/app.resolver.ts#L10

You can use this tool to see the session data in redis.

https://redisdesktop.com/

For whatever reason, a brand new session is created on every graphql request, but the session works fine when using controllers.

**Comment by codejamninja** [comment]
Also, default username is `admin` and default password is `pass`.

**Comment by codejamninja** [comment]
The session works fine from the controller.

https://github.com/codejamninja/appsaas-core/blob/master/src/controllers/app.controller.ts#L20

**Comment by iamolegga** [comment]
All right I'll try to dig into it in a next few days

**Comment by iamolegga** [comment]
At least for now you can try move `SessionModule` with `RedisModule` before `GraphQLModule`, maybe it would help

**Comment by codejamninja** [comment]
I was wondering if maybe it's a cors issue?

**Comment by codejamninja** [comment]
@iamolegga moving the file didn't help. I tried adding `passport-session` directly in the `main.ts` file, but I have the same problem.

**Comment by iamolegga** [comment]
> I was wondering if maybe it's a cors issue?

Can't say now, but I think it would be easier if you could copy that repo and reduce modules and left only graphql and session packages 🙂

> moving the file didn't help. I tried adding passport-session directly in the main.ts file, but I have the same problem.

That will not work, because `passport.session()` should be after call of `express-session`

**Comment by codejamninja** [comment]
It is after it.

https://github.com/codejamninja/appsaas-core/blob/master/src/main.ts#L34

I’ll see if I can create a simpler example.

**Comment by codejamninja** [comment]
I figured out the issue. The problem was because the graphql playground was not sending the cookie. I fixed it with the following settings.

```ts
  playground: {
    settings: {
      "request.credentials": "include"
    }
  }
```
