### ISSUE TITLE
How can we access the session middleware?

### ISSUE THREAD

**Issue by drthoben** [iamolegga/nestjs-session#296]
Because the express-session middleware is created from within the `createModule` closure it is not possible to access the middleware from another place.

Or is it?

**Comment by iamolegga** [comment]
No, that's not possible so far. What's the reason you want to access it?

**Comment by drthoben** [comment]
I'm using your package along with a GraphQL server. As the websockets themselves do not contain any cookies I'm using the `onAccept()` function to create the context for the incoming websocket connection but unfortunately I don't have access to the session in the `upgradeReq` object and also no access to the middleware to process the upgradeReq. I'd like to use the middleware like this:
```
  subscriptions: {
    onConnect: (connectionParams, websocket: any) => {
      return new Promise((resolve) => {
        sessionMiddleware(websocket.upgradeReq, {} as any, () => {
          resolve({ req: websocket.upgradeReq });
        });
      });
    },
  },
```

**Comment by iamolegga** [comment]
This is a bit more complex usage than was expected at start. But feel free to open feature request for this in [parent lib repo](https://github.com/iamolegga/create-nestjs-middleware-module), bacause this is more general feature, and not higly coupled to current lib. Thanks
