### ISSUE TITLE
[BUG] Depracation warnings

### ISSUE THREAD

**Issue by kkoomen** [iamolegga/nestjs-session#317]
After integrating this into my Nest  project we ran into these warnings. Could you resolve them please?

```
Fri, 18 Dec 2020 04:00:02 GMT express-session deprecated undefined resave option; provide resave option at node_modules/nestjs-session/dist/index.js:8:22

Fri, 18 Dec 2020 04:00:02 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at node_modules/nestjs-session/dist/index.js:8:22
```

**Comment by iamolegga** [comment]
Closing this issue, this is not a bug, the message is absolutely clear: carefully read the docs of `express-session` and set `resave` and `saveUninitialized` fields
