### ISSUE TITLE
[QUESTION] How to use this session in a NestJS GraphQL resolver?

### ISSUE THREAD

**Issue by spemmons** [iamolegga/nestjs-session#392]
I'm trying to find a good way to use session data (not for authentication) NestJS GraphQL resolvers, but not having any luck.

Any pointers/suggestions? Thanks!

**Comment by iamolegga** [comment]
I believe it should work pretty same as for standard controllers, feel free to provide a minimal example repo, you can start with [basic example](https://github.com/iamolegga/nestjs-session/tree/master/examples/in-memory) and add hello world resolver

**Comment by iamolegga** [comment]
closing, feel free to continue the discussion

**Comment by frct1** [comment]
Try this snippet:
```ts
export const Session = createParamDecorator(
  (data, ctx: ExecutionContext) => {
    let req;
    if (ctx.getType() == 'http') {
      req = ctx.switchToHttp().getRequest();
    }
    if (ctx.getType<GqlContextType>() == 'graphql') {
      req = GqlExecutionContext.create(ctx).getContext().req;
    }
    return req.session;
  },
);
```
